### ISSUE TITLE
Neaiškios Docker pasileidimo vietos po migracijos į Symfony4

### ISSUE THREAD

**Issue by aurelijusbanelis** [nfqakademija/kickstart#23]
Atsiliepimai iš komandų:
- [x] Neaiškios slaptažodžių pakeitimo vietos
- [x] fixuoti port'ai (per daug žmonių turi pasileidę `apache`, `MySql` ar pan.
- [x] senas `frondned` konteineris neištrinamas (trūksta `--rm`)
- [x] Naišku, kai pereinama tarp `php` ir `frontend` konteinerių (norima leisti komandas tame pačiame konteineryje
- [x] `docker-compose` `APP_ENV=prod` neaišku kodėl (reikėtų atskirti į atskirus stack'us)
- [x] dokumentuoti `env.dist`
- [x] tavis integracija (`docker` teisės)
- [x] perkelti `./docker/docker-compose.yml` (nes vis lieka kažkur sena dokumetnaicja)
- [x] `docker-compose kill` neveikia (`./docker/docker-compose.yml` numigruotas)
- [x] atskirti suk4limui į serverį failus (kad nesimaišytų nuo kodo)

Susiję: https://github.com/nfqakademija/kickstart/pull/20, https://github.com/nfqakademija/kickstart/pull/22

Prie progos prisėsiu, pataisyti. Jei yra daugiau pasiūlymų, papildykite...

**Comment by gitazemguliene** [comment]
perkelti ./docker/docker-compose.yml (nes vis lieka kažkur sena dokumetnaicja)
docker-compose kill neveikia (./docker/docker-compose.yml numigruotas)

šitų vistik gal nreikia, nes vistik problema tik dokumentacijo... O dokumentacija pataisyta

**Comment by aurelijusb** [comment]
Neskaitant `travis` kaip ir viskas turėtų būti pataisyta

**Comment by aurelijusb** [comment]
Travis irgi sutvarkytas: https://travis-ci.org/nfqakademija/kickstart/builds/363228515

Daugiau problemų nesimato
