### ISSUE TITLE
Dažnaiusios deploy klaidos

### ISSUE THREAD

**Issue by aurelijusbanelis** [nfqakademija/kickstart#27]
- `.deploy/hosts` - `ansible_user=kickstart` vietoj kickstart savo komandos useris
- `Makefile` - prie `ARTIFACT_INCLUDES` prideti `translations` (jei naudojamas translations bundle), nes kitaip failina cache:clear (neranda translations diro)
- `.env.dist` nėra kopijuojamas, todėl specialios `.env.dist` reikšmės turi būti pakeistos `shared/.env` faile rankomis prisi`ssh`inus (Kontekstui: https://github.com/nfqakademija/kickstart/blob/master/.deploy/playbook.yaml#L9)
- Sena `composer.json` naudoja `symfony/dotenv` kaip `require-dev` – bet serverio konfiguracija tikisi, kad būtų prie ir produkcinėje versijoje (`requruire` dalyje)
- Jei gaunate, klaidą, kad neranda kažkokio katalogo, turbūt nepridėjote jo pavadinimo į `ARTIFACT_INCLUDES` faile `Makefile` (pvz. problemos su`translations` katalogu)
- Pavyzdyje gali būti likusi klaida su `linked_files: - shared/.env`, jei gaunate `if you really want to create the link: /home/.../shared/shared/.env`, reikėtų vietoj `shared/.env` naudoti tiesiog `.env`

**Comment by aurelijusb** [comment]
Beveik visos išspręstos su https://github.com/nfqakademija/kickstart/pull/31
