### ISSUE TITLE
Document debugging

### ISSUE THREAD

**Issue by mariusgrigaitis** [nfqakademija/kickstart#3]
How to setup environment with debugging? I don't see it mentioned in documentation.

**Comment by saimaz** [comment]
This topic is still not implemented. You are welcome to make PR about this. However, I believe debugging will be implemented in a few weeks.

**Comment by aurelijusb** [comment]
Instruction: https://github.com/nfqakademija/docker/pull/1

Link in documentation will be added in https://github.com/nfqakademija/kickstart/pull/28
