### ISSUE TITLE
No way to manage php extensions

### ISSUE THREAD

**Issue by spaivaras** [nfqakademija/kickstart#6]
There is no way to manage php extensions in fpm container. There is a "hack" in base image, still containers will not persist data even if extensions are installed.

Details:
- OS: Any
- Docker version: Any

**Comment by saimaz** [comment]
Well, it's not true. `kickstart` uses docker image from https://github.com/saimaz/docker-fpm. Anyone can open PR and add any extension they need. Also, nobody forbids to add `Dockerfile` to the project by extending `nfqakademija/fpm` and creating a build for this container.

**Comment by spaivaras** [comment]
The problem with PR's to images are few. Like: my required module, would be also "available" for everyone else. When doing live/stage server requests its always nice to exactly know what you need. In any case the solution to extending  your own image is quite suitable in this case, so the issue could be closed, from my side

**Comment by saimaz** [comment]
IMO maybe would be nice to provide an example how to extend the image.

**Comment by saimaz** [comment]
PHP-FPM container builds from local Docker image file. If anyone wants an extension, it can be easily added through there.
