### ISSUE TITLE
npm container has no entrypoint

### ISSUE THREAD

**Issue by spaivaras** [nfqakademija/kickstart#7]
npm container, exists every time a custom command is executed. Running container for each npm action and will just spam with new container and volumes. This just bloats ups space usage. A simple fix would be to add even a dummy entry point like "sleep infinity" that will keep a single container active, and docker-compose exec will be able to reuse npm container
 
Details:
- OS: Any
- Docker version: Any

**Comment by saimaz** [comment]
May you create a PR in https://github.com/saimaz/docker-node

**Comment by saimaz** [comment]
Solved.
